# Generated by Django 4.1.4 on 2023-01-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                ("rating", models.IntegerField()),
                ("is_best_selling", models.BooleanField(default=False)),
                ("author", models.CharField(max_length=100, null=True)),
                ("slug", models.SlugField(default="")),
            ],
        ),
    ]
