# Generated by Django 4.1.4 on 2023-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="currency",
            field=models.CharField(default="RUB", max_length=3),
        ),
    ]
