# Generated by Django 4.1.4 on 2023-01-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0005_book_author_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
    ]
