# Generated by Django 4.1.4 on 2023-01-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0006_remove_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author_contact",
            new_name="author",
        ),
    ]
