# Generated by Django 4.1.4 on 2023-01-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0007_rename_author_contact_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heroes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужчина"), ("F", "Женщина")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="heroes",
            field=models.ManyToManyField(to="book_app.heroes"),
        ),
    ]
