# Generated by Django 4.1.4 on 2023-01-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0010_alter_book_author_alter_book_heroes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="heroes",
            field=models.ManyToManyField(to="book_app.heroes"),
        ),
    ]
